# é¡µé¢å³ä¸Šæ–¹çš„å‡ ä¸ªé“¾æ¥ï¼Œkeyéšä¾¿å†™ã€‚
topbar:
  homepage: # è¿™ä¸ªå­—æ®µéšä¾¿å†™
    name: å¯¼èˆªé¡µ
    url: https://cayzlh.github.io
  github:
    name: GitHub
    url: https://github.com/cayzlh
    target: _blank
  about:
    name: å…³äº
    url: /about

# èœå•é…ç½®ï¼ŒKeyéšä¾¿å†™ï¼Œæ”¯æŒå­èœå•
menu:
  Home:
    url: /
    name: é¦–é¡µ
  Archives:
    url: /archives
    name: å½’æ¡£
  Tools:
    url: /
    name: åœ¨çº¿å·¥å…·
    children:
      - name: Jsonåœ¨çº¿å·¥å…·
        url: https://cayzlh.github.io/tools/online-JSONFormat/
      - name: Markdownåœ¨çº¿è½¬æ¢å·¥å…·
        url: https://cayzlh.github.io/tools/online-markdown/

# slogan å’Œ ä¸‹é¢çš„ä¸€æ’é“¾æ¥é…ç½®ï¼Œä¸é…ä¸æ˜¾ç¤º
jumbotron:
  slogan: è®°å½•æˆé•¿è·¯ä¸Šçš„é£æ™¯
  infos:
    - name: å¯Œå¼º
      url: /
    - name: æ°‘ä¸»
      url: /
    - name: æ–‡æ˜
      url: /
    - name: å’Œè°
      url: /
    - name: è‡ªç”±
      url: /
    - name: å¹³ç­‰
      url: /
    - name: å…¬æ­£
      url: /
    - name: æ³•åˆ¶
      url: /
    - name: çˆ±å›½
      url: /
    - name: æ•¬ä¸š
      url: /
    - name: è¯šä¿¡
      url: /
    - name: å‹å–„
      url: /

# ç¤¾äº¤é“¾æ¥ï¼Œicon å’Œ txt äºŒé€‰ä¸€
social:
  - url: https://github.com/cayzlh
    target: _blank
    icon: fa-github
    txt:
  - url: https://twitter.com/Q2F5emxo
    target: _blank
    icon: fa-twitter
    txt:
  - url: mailto:chenanyu@cayzlh.com
    target: _blank
    icon:
    txt: é‚®

# åšå®¢çš„faviconå›¾æ ‡ï¼Œæ”¯æŒå„ç§æ ¼å¼
favicon: /favicon.svg

# å±•ç¤ºç²¾é€‰æ–‡ç« , éœ€åœ¨æ–‡ç« ä¸­æ·»åŠ  favorite: true å±æ€§
favorites:
  enable: true # æ˜¯å¦å±•ç¤ºç²¾é€‰æ–‡ç« 
  title: ç²¾é€‰æ–‡ç«  # æ ‡é¢˜
  num: 6  # å±•ç¤ºå¤šå°‘ä¸ªï¼Œ å»ºè®®ä¸è¦å¤ªå¤š

# å±•ç¤ºå¼€æºé¡¹ç›®ï¼ˆGitHubï¼‰
openSource:
  enable: false # æ˜¯å¦å±•ç¤º
  title: å¼€æºè½¯ä»¶
  username: cayzlh # githubç”¨æˆ·åï¼Œç”¨äºå±•ç¤ºstars å’Œ forksæ•°
  repos:
    - url: https://github.com/cayzlh/hexo-theme-yummy
      name: hexo-theme-yummy # repoçš„åç§°ï¼Œä¸€å®šè¦å¡«å¯¹
      title: hexo-theme-yummy # å±•ç¤ºåˆ°é¡µé¢çš„åç§°
      description: ç§»æ¤è‡ªJekyllçš„ä¸€æ¬¾hexoä¸»é¢˜

# æ˜¯å¦ç™½å«–cdnåŠ é€Ÿï¼Œæœ¬åœ°è°ƒè¯•æ ·å¼ä¹‹ç±»çš„è®°å¾—è®¾ç½®æˆfalse
jsDelivr:
  enable: false
  url: https://cdn.jsdelivr.net/gh/yourgithubname/yourreponame@master # è®°å¾—è¦æ›¿æ¢æˆä½ çš„åœ°å€

# googleç›¸å…³é…ç½®
google:
  analytics:  # google åˆ†æ
    enable: false
    id: # google analytics ID
  verification: # éªŒè¯
    enable: false
    id: # google ç«™ç‚¹éªŒè¯ï¼Œå¡«ä½ çš„

ICP: # äº¬ICPå¤‡123456789å·

top:
  enable: true # æ˜¯å¦å¼€å¯å›åˆ°æœ€ä¸Šé¢

# æ˜¯å¦å±•ç¤ºé¡µé¢å·¦ä¸‹è§’çš„rssåŒºåŸŸ
rss:
  enable: true

# è‡ªå®šä¹‰å½’æ¡£é¡µé¢çš„æ ‡é¢˜å’Œå‰¯æ ‡é¢˜
archive:
  title: All My Blogs
  subtitle: Record the scenery on the road of growth

# åˆ†ç±»é¡µé¢è®¾ç½®ï¼Œç”¨äºæŒ‡å®šåˆ†ç±»é¡µçš„å…ƒç´ çš„å±•ç¤º
category:
  enable: false
  Git: # æ¯ä¸ªKeyè¦å†™å¯¹åº”åˆ†ç±»çš„åç§°ï¼Œæ¯”å¦‚åˆ†ç±»ä¸ºGitçš„é¡µé¢å°±å¦‚æ¡ˆä¾‹æ‰€ç¤ºé…ç½®
    title: Gitç›¸å…³æ–‡ç« 
    subtitle: gitæ“ä½œç›¸å…³çš„æ–‡ç« 

# æ ‡ç­¾é¡µé¢è®¾ç½®ï¼Œç”¨äºæŒ‡å®šæ ‡ç­¾çš„å…ƒç´ çš„å±•ç¤º
tag:
  enable: false
  Docker:
    title: Docker~~~
    subtitle: docker~~~

# é¡µé¢ä¸‹æ–¹copyrightè®¾ç½®
copyright:
  enable: true
  name: ğŸ³Antä¸¶
  since: 2020

# æ–‡ç« ç»“å°¾è®¾ç½®
postending:
  enable: true # æ˜¯å¦å¯ç”¨
  image: true # æ˜¯å¦åœ¨æ–‡ç« ç»“å°¾æ˜¾ç¤ºä¸€ä¸ªå›¾ç‰‡
  declaration: # æ˜¯å¦åœ¨æ–‡ç« ç»“å°¾æ˜¾ç¤ºç‰ˆæƒå£°æ˜
    enable: true
    copyright: # ç‰ˆæƒå£°æ˜ã€‚ä¸é…åˆ™ç”¨é»˜è®¤çš„æ–‡æ¡ˆã€‚æ”¯æŒhtmlä»£ç ç‰‡æ®µ

# busuanziç»Ÿè®¡
busuanzi:
  enable: true
  site: # ç«™ç‚¹ç»Ÿè®¡é…ç½®
    pv: true # å±•ç¤ºç«™ç‚¹è®¿é—®æ¬¡æ•°
    uv: true # å±•ç¤ºç«™ç‚¹è®¿é—®äººæ¬¡
  post: # æ–‡ç« ç»Ÿè®¡é…ç½®
    pv: true # å±•ç¤ºæ–‡ç« é˜…è¯»æ¬¡æ•°

# è¯„è®ºç³»ç»Ÿï¼Œå¼€å¯ç›¸åº”çš„è¯„è®ºç³»ç»Ÿï¼Œ å°†ä¼šåœ¨ä½ çš„æ–‡ç« ä¸‹æ–¹å±•ç¤ºè¯„è®ºï¼Œä¹Ÿå¯ä»¥ç”¨æ–‡ç« å±æ€§ comments æ¥æ§åˆ¶
comment:
  enable: false  # æ˜¯å¦å¼€å¯
  gitalk: # gitalk
    enable: false
    owner: # 'ä½ çš„ GitHub ID',
    repo: # 'å­˜å‚¨è¯„è®ºçš„ repo',
    oauth:
      clientId: # 'ä½ çš„ client ID'
      clientSecret: # 'ä½ çš„ client secret',
    admin:
  gitment: # gitment
    enable: false
    owner: # 'ä½ çš„ GitHub ID',
    repo: # 'å­˜å‚¨è¯„è®ºçš„ repo',
    oauth:
      client_id: # 'ä½ çš„ client ID'
      client_secret: # 'ä½ çš„ client secret',
  valine: # Valine è¯„è®ºæ¨¡å—çš„é…ç½®ï¼Œé»˜è®¤ä¸ºä¸æ¿€æ´»ï¼Œå¦‚è¦ä½¿ç”¨ï¼Œå°±è¯·æ¿€æ´»è¯¥é…ç½®é¡¹ï¼Œå¹¶è®¾ç½® appId å’Œ appKey.
    enable: false
    appId: # ä½ çš„appid
    appKey: # ä½ çš„appkey
    notify: false
    verify: false
    visitor: true
    avatar: 'mm' # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
    pageSize: 10
    placeholder: 'just go go' # Comment Box placeholder
    guest_info: nick,link,mail # Comment header info

# å¯ç”¨ç›¸å…³æ–‡ç« æ¨è
popular_posts:
  enable: false
  title: ç›¸å…³æ¨è
  max: 6

# å…¬ä¼—å·å¼•æµï¼Œä½¿ç”¨æ’ä»¶ https://github.com/snowdreams1006/hexo-plugin-readmore
# éœ€è¦å» https://my.openwrite.cn æ³¨å†Œä¸€ä¸ªè´¦å·å¹¶å¼€é€šå¢é•¿å·¥å…·ï¼šåšå®¢å¯¼æµå…¬ä¼—å·
readmore:
  enable: false # å¼€å¯è¿™ä¸ªåŠŸèƒ½ï¼Œé™¤äº†åœ¨ä¸»é¢˜é…ç½®æ–‡ä»¶ä¸­é…ç½®ä»¥å¤–ï¼Œè¿˜éœ€è¦é…ç½®æ–‡ç« å±æ€§çš„å½±å“ï¼Œéœ€è¦åœ¨æ–‡ç« ä¸­æ·»åŠ å±æ€§ï¼š`readmore: true`
  blogId: # å¡«å†™å·²ç”³è¯·çš„åšå®¢ id
  name:  # å¡«å†™å·²ç”³è¯·çš„åšå®¢åç§°
  qrcode: # å¡«å†™å·²ç”³è¯·çš„å…¬ä¼—å·äºŒç»´ç é“¾æ¥
  keyword: # å¡«å†™å·²ç”³è¯·çš„å…¬ä¼—å·å›å¤å…³é”®å­—