topbar:
  categories:
    name: åˆ†ç±»
    url: /categories/
  tags:
    name: æ ‡ç­¾
    url: /tags/
  meiriyiwen:
    name: æ¯æ—¥ä¸€æ–‡
    url: https://meiriyiwen.com/random
    target: _blank
  github:
    name: é“¾æ¥
    url: /links/
  about:
    name: å…³äº
    url: /about

menu:
  Home:
    url: /
    name: Home
  Archives:
    url: /archives
    name: Archives
  books:
    url: /
    name: Learning
    children:
      - name: æ·±å…¥ç†è§£Javaè™šæ‹Ÿæœº
        url: /categories/ä¹¦ç±/ã€Šæ·±å…¥ç†è§£Javaè™šæ‹Ÿæœºã€‹/
      - name: MyBatisæŠ€æœ¯å†…å¹•
        url: /categories/ä¹¦ç±/ã€ŠMyBatisæŠ€æœ¯å†…å¹•ã€‹/
      - name: Javaè®¾è®¡æ¨¡å¼
        url: /categories/Java/Javaè®¾è®¡æ¨¡å¼/
  Tools:
    url: /
    name: Tools
    children:
      - name: Jsonåœ¨çº¿å·¥å…·
        url: https://www.cayzlh.com/tools/online-JSONFormat/
        target: _blank
      - name: Markdownåœ¨çº¿è½¬æ¢å·¥å…·
        url: https://www.cayzlh.com/tools/online-markdown/
        target: _blank
      - name: åœ¨çº¿HASH
        url: https://www.cayzlh.com/tools/online-hash/
        target: _blank

jumbotron:
  slogan: NOTEBOOK
  infos:
    - name: Java
      url: /categories/Java/
    - name: Spring Code
      url: /categories/Spring/ã€ŠSpringæºç åˆ†æã€‹/
    - name: SpringBoot
      url: /tags/SpringBoot/
    - name: SpringCloud
      url: /categories/Spring/SpringCloud/
    - name: Docker
      url: /tags/Docker/
    - name: Linux
      url: /tags/Linux/
    - name: é›•è™«å°æŠ€
      url: /categories/é›•è™«å°æŠ€/


social:
  - url: https://github.com/cayzlh
    target: _blank
    icon: fa-github
    txt:
  - url: https://www.zhihu.com/people/chenanyu
    target: _blank
    icon:
    txt: çŸ¥
  - url: mailto:Q2F5emxo@cayzlh.com
    target: _blank
    icon: fa-envelope
    txt:

favicon: /favicon.svg

# å±•ç¤ºç²¾é€‰æ–‡ç« , éœ€åœ¨æ–‡ç« ä¸­æ·»åŠ  favorite: true å±æ€§
favorites:
  enable: true # æ˜¯å¦å±•ç¤ºç²¾é€‰æ–‡ç« 
  title: favorite posts # æ ‡é¢˜
  num: 6  # å±•ç¤ºå¤šå°‘ä¸ªï¼Œ å»ºè®®ä¸è¦å¤ªå¤š

# å±•ç¤ºå¼€æºé¡¹ç›®ï¼ˆGitHubï¼‰
openSource:
  enable: true
  title: open sources
  username: cayzlh # githubç”¨æˆ·åï¼Œç”¨äºå±•ç¤ºstars å’Œ forksæ•°
  repos:
    - url: https://github.com/cayzlh/cayzlh-starters
      name: cayzlh-starters # repoçš„åç§°ï¼Œä¸€å®šè¦å¡«å¯¹
      title: cayzlh-starters # å±•ç¤ºåˆ°é¡µé¢çš„åç§°
      description: ç”±ä¸ªäººå°è£…çš„ä¸€äº›springboot starteré¡¹ç›®
    - url: https://github.com/cayzlh/hexo-theme-yummy
      name: hexo-theme-yummy
      title: hexo-theme-yummy
      description: ç§»æ¤äº†ä¸€ä¸ªjekyllä¸»é¢˜åˆ°Hexo

# æ˜¯å¦ç™½å«–cdnåŠ é€Ÿï¼Œæœ¬åœ°è°ƒè¯•æ ·å¼ä¹‹ç±»çš„è®°å¾—è®¾ç½®æˆfalse
jsDelivr:
  enable: false
  url: https://cdn.jsdelivr.net/gh/cayzlh/blog@master

google:
  analytics:
    enable: true
    id: UA-129095667-1
  verification:
    enable: true
    id: VrcbMTVpFGlHkIERHBt753dAtXKF4qirjnDweuXSRJw

ICP: ç²¤ICPå¤‡20058712å·-1

top:
  enable: false # æ˜¯å¦å¼€å¯å›åˆ°æœ€ä¸Šé¢

rss:
  enable: false

archive:
  title: All My Posts
  subtitle: Record the scenery on the road of growth

# åˆ†ç±»é¡µé¢è®¾ç½®ï¼Œç”¨äºæŒ‡å®šåˆ†ç±»é¡µçš„å…ƒç´ çš„å±•ç¤º
category:
  enable: true
  ã€ŠSpringæºç åˆ†æã€‹: # æ¯ä¸ªKeyè¦å†™å¯¹åº”åˆ†ç±»çš„åç§°
    title:
    subtitle:
    sortType: asc

# æ ‡ç­¾é¡µé¢è®¾ç½®ï¼Œç”¨äºæŒ‡å®šæ ‡ç­¾çš„å…ƒç´ çš„å±•ç¤º
tag:
  enable: false
  Docker:
    title: Docker~~~
    subtitle: docker~~~

# é¡µé¢ä¸‹æ–¹copyrightè®¾ç½®
copyright:
  enable: true
  name: ğŸ³Antä¸¶
  since: 2020
  link: https://www.cayzlh.com

# æ–‡ç« ç»“å°¾è®¾ç½®
postending:
  enable: true # æ˜¯å¦å¯ç”¨
  image: true # æ˜¯å¦åœ¨æ–‡ç« ç»“å°¾æ˜¾ç¤ºä¸€ä¸ªå›¾ç‰‡
  declaration: # æ˜¯å¦åœ¨æ–‡ç« ç»“å°¾æ˜¾ç¤ºç‰ˆæƒå£°æ˜
    enable: true
    copyright: æ–‡ç« å†…å®¹ä»…ç”¨ä½œå­¦ä¹ å’Œåˆ†äº«ï¼Œå¦‚æœ‰é›·åŒï¼Œçº¯å±æ‹·è´ã€‚


# busuanziç»Ÿè®¡
busuanzi:
  enable: true
  site:
    pv: false # å±•ç¤ºç«™ç‚¹è®¿é—®æ¬¡æ•°
    uv: false # å±•ç¤ºç«™ç‚¹è®¿é—®äººæ¬¡
  post:
    pv: false

# è¯„è®ºç³»ç»Ÿï¼Œå¼€å¯ç›¸åº”çš„è¯„è®ºç³»ç»Ÿï¼Œ å°†ä¼šåœ¨ä½ çš„æ–‡ç« ä¸‹æ–¹å±•ç¤ºè¯„è®ºï¼Œä¹Ÿå¯ä»¥ç”¨æ–‡ç« å±æ€§ comments æ¥æ§åˆ¶
comment:
  enable: true  # æ˜¯å¦å¼€å¯
  gitalk: # gitalk
    enable: false
    owner: Cayzlh # 'ä½ çš„ GitHub ID',
    repo: blog # 'å­˜å‚¨è¯„è®ºçš„ repo',
    oauth:
      clientId: 2ac39145d111667ffeae # 'ä½ çš„ client ID'
      clientSecret: 18e575652c197c59a751b13025e07ef7a6eaac63 # 'ä½ çš„ client secret',
    admin: ['Cayzlh']
  gitment: # gitment
    enable: false
    owner: # 'ä½ çš„ GitHub ID',
    repo: # 'å­˜å‚¨è¯„è®ºçš„ repo',
    oauth:
      client_id: # 'ä½ çš„ client ID'
      client_secret: # 'ä½ çš„ client secret',
  valine:
    enable: true # å¦‚æœä½ æƒ³ä½¿ç”¨valineï¼Œè¯·å°†å€¼è®¾ç½®ä¸º true
    appId: rEPr8FnwPatAARVnsKDFdvtI-gzGzoHsz # your leancloud appId
    appKey: 7rsPiBWwuRFgagw214Esafmw # your leancloud appKey
    notify: false # Mail notify
    verify: false # Verify code
    visitor: true
    avatar: identicon # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
    placeholder: ç©¿å±±ç”²åˆ°åº•è¯´äº†å•¥ï½ # Comment Box placeholder
    guest_info: nick,link,mail # Comment header info
    pageSize: 10 # comment list page size

# ç›¸å…³æ–‡ç« æ¨è
popular_posts:
  enable: true
  title: ç›¸å…³æ¨è
  max: 6

# å…¬ä¼—å·å¼•æµï¼Œéœ€è¦æ’ä»¶ https://github.com/snowdreams1006/hexo-plugin-readmore
readmore:
  enable: true
  blogId: 22460-1590656129246-152
  name:  CAYZLH
  qrcode: https://gitee.com/cayzlh/img-repo/raw/master/2020/05/29/qrcode_for_gh_829ddbb5b729_430-2_Ye9NBi.jpg
  keyword: more